# Generated by Django 4.2.19 on 2025-02-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('available_seats', models.PositiveIntegerField()),
            ],
        ),
    ]
